swagger: "2.0"
info:
  description: "This is a movie search api"
  version: "1.0.0"
  title: "Movie search"
  contact:
    email: "movie@search.com"
host: "localhost:3000"
basePath: "/"
tags:
- name: "movie"
  description: "Everything about movies"
paths:
  /movies/search:
    get:
      tags:
      - "movie"
      summary: "Search for movies"
      description: ""
      operationId: "searchMovies"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "q"
        description: "Search term for movie database search"
        required: true
        type: "string"
      responses:
        404:
          description: "Movie not found"
        200:
          description: "Movie found"
      